site_name: FCMC
extra_javascript:
  - javascript/script.js
extra_css:
  - css/styles.css
theme:
  name: material
  palette:
    primary: blue grey
  logo: img/sand.png
  favicon: img/sand.png
nav:
  - Home: index.md
  - World Map: http://108.62.104.82:57557/
  - Getting Started: getting_started.md
  - Plugins: plugins.md