site_name: FCMC
extra_javascript:
  - javascript/script.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - css/styles.css
theme:
  name: material
  palette:
    primary: blue grey
  logo: img/sand.png
  favicon: img/sand.png
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
nav:
  - Home: index.md
  - World Map: http://108.62.104.82:38305/?worldname=new-world-1.18&mapname=flat&zoom=3&x=250&y=64&z=250
  - Getting Started: getting_started.md
  - Plugins: plugins.md
  - Lands:
    - Claiming & Managing Land: ./lands/claiming_land.md
    - Inviting Others to Your Land: ./lands/inviting_friends.md
    - Leveling up Your Civilization: ./lands/leveling_up_your_civilization.md
    - Declaring War: ./lands/declaring_war.md
  - Custom Recipes: custom_recipes.md
  - Waypoints: waypoints.md